### ISSUE TITLE
"Return raffle tickets" not working properly

### ISSUE THREAD

**Issue by zeventhing** [nobodyrandom/mhAutobot#12]
Hi NobodyRandom,
regarding this "raffle tickets" issue,

---- start:from_email
Hi,
Sorry for the late reply. I have checked the code for the raffle ticket, and it "should" select the raffle tab, can I get a screenshot for which tab is selected.
---- end:from_email

The answer is "yes, exactly" for ..
".... and it "should" select the raffle tab" , but after the raffle tab selected, the bot doesn't click the [Send Raffle] like it was supposed to.

**Comment by nobodyrandom** [comment]
OK I'll double check that part of the code

**Comment by nobodyrandom** [comment]
Ok just pushed a new update, it should fix the raffle for both OLD and NEW UI

**Comment by nobodyrandom** [comment]
Please confirm issue is resolved

**Comment by zeventhing** [comment]
For the love of God, it works!
I really like what you are doing. Keep up the good work!
Cheers~!

(BUG RESOLVED)
