### ISSUE TITLE
kr sound issue 

### ISSUE THREAD

**Issue by mousehunt** [nobodyrandom/mhAutobot#13]
seems like the devs has upgraded their kr system, every time there is a kr, a pop up like this (http://prntscr.com/6l4z8s) will show up, the sound will not work until click the "ok". Any fix for this? thanks

**Comment by nobodyrandom** [comment]
Give me 3 hours and I'll push a fix by then

**Comment by nobodyrandom** [comment]
One thing, can you tell me which version of the bot you are using?

**Comment by mousehunt** [comment]
version 1.3.037z thanks

**Comment by mousehunt** [comment]
sorry, is  (version 1.5.067y)

**Comment by nobodyrandom** [comment]
OK patched and pushed an update
Pushing updates to other vers in a sec

**Comment by nobodyrandom** [comment]
Please confirm on your next KR that bug is fixed

**Comment by mousehunt** [comment]
still same...

**Comment by nobodyrandom** [comment]
BTW the popup is a function added to the bot, you can turn it off on the preferences.

This was just to force users onto the MH window when KR happens.

The last patch I pushed should've triggered the popup AFTER the sound....

**Comment by mousehunt** [comment]
it is fixed, thank you
