### ISSUE TITLE
FF script timing issue (G Express)

### ISSUE THREAD

**Issue by darkn123** [nobodyrandom/mhAutobot#16]
Seems broken on the 2.0.22b

FF 38
Greasemonkey 3.2

**Comment by nobodyrandom** [comment]
Please use ver 2.1.1

**Comment by nobodyrandom** [comment]
OK will check.

**Comment by nobodyrandom** [comment]
btw did it work before any updates or what so ever?

**Comment by nobodyrandom** [comment]
Found some timing errors on FF, will fix after release of 2.1.1a/b/y please give me 2 weeks or so.

**Comment by darkn123** [comment]
Not sure, i havnt tried it prior

When i check the debug console, i see this 
"Parse login failed, attempting to create new user now."

Mousehuntgame.com btw
What does this mean?

**Comment by nobodyrandom** [comment]
Its just the support script on the bot.. It allows the usage of timers and gDoc etc

**Comment by nobodyrandom** [comment]
Huge FF fix on 2.1.11a/b, please confirm this issue is fixed @darkn123
