### ISSUE TITLE
New update 2.1.6a doesn't work for firefox

### ISSUE THREAD

**Issue by blaze1991** [nobodyrandom/mhAutobot#18]
I'm running it on greasemonkey and before the update to 2.1.6a it works fine. Hope you can solve this soon thanks!

**Comment by nobodyrandom** [comment]
Ok this is news, can I get more details on it?

**Comment by nobodyrandom** [comment]
Actually just found the bug

ISSUE FIXED ON VER 2.1.7a/b

**Comment by nobodyrandom** [comment]
Please confirm bug is fixed

**Comment by nobodyrandom** [comment]
2.1.11a/b also has a huge FF fix. Please update to it asap, and confirm this issue no longer exists @blaze1991

**Comment by blaze1991** [comment]
the 2.1.6 bug is fixed and works fine on FF. however, 2.1.12a on FF still refuses to let me submit to the gdoc. I can open the g doc (opens a javascript tab and the gdoc tab but at least it works, but submission to the gdoc via the link on the bot doesn't work. 

On chrome I can submit as long as I'm in the garden area (showing number of essence etc.) I suppose that's the intended function.

**Comment by nobodyrandom** [comment]
On ff, they dont support the innerText function... No idea why they wouldn't support the function. But untill they do, a bypass to this will be very difficult.

**Comment by nobodyrandom** [comment]
Ill see if i can fix the new tab issue for now.

**Comment by darkn123** [comment]
Event/locations do not work in 2.1.16b
Latest FF and GM
Ive tried in brift/ges, it doesnt change trap/mist/charms etc
All it does is simply horn

What i see in web console:
Running Burroughs Rift(Red) bot."
document.getElementById('scriptElement').innerText=user.location;"
