### ISSUE TITLE
kr sound inquiry 

### ISSUE THREAD

**Issue by mousehunt** [nobodyrandom/mhAutobot#20]
hi, my kr sound stop working since yesterday, when i check my setting i saw this: http://prntscr.com/81kiek

how is it work? 

Thank you.

**Comment by nobodyrandom** [comment]
OK I'll push an update to fix the link... theres supposedly something in there but i think the save setting is broken lol

**Comment by nobodyrandom** [comment]
Just pushed 2.1.15 which should fix it. Pls confirm

**Comment by mousehunt** [comment]
sorry for the delay, was sleeping. I think it is fix now, thanks. another question, is it possible to use other song for kr? I mean all i need to do is use a mp3 link and paste it in the "King Reward Sound" field right?

thank you.

**Comment by nobodyrandom** [comment]
Yep it should work as long as the link ends with .mp3

**Comment by mousehunt** [comment]
thank you!
