### ISSUE TITLE
2.1.16b - Events/location not working in FF

### ISSUE THREAD

**Issue by darkn123** [nobodyrandom/mhAutobot#21]
Event/locations do not work in 2.1.16b
Latest FF and GM
Ive tried in brift/ges, it doesnt change trap/mist/charms etc
All it does is simply horn

What i see in web console:
Running Burroughs Rift(Red) bot."
document.getElementById('scriptElement').innerText=user.location;"

**Comment by nobodyrandom** [comment]
OK will get to it tomorrow. Seems like a timing issue to me, but ill check

**Comment by nobodyrandom** [comment]
OK seems to be a problem with firefox... will patch asap.

**Comment by nobodyrandom** [comment]
I have fixed ~60% of the bots for firefox.

GES should be working for now, will check the other areas after.
Bug due to FF not supporting .innerText

**Comment by darkn123** [comment]
2.1.18b

Charms are not being armed at GES

**Comment by nobodyrandom** [comment]
Need some more info:
What were you arming before?
What should the bot be arming?
Any error on console log?

**Comment by darkn123** [comment]
Super power
Supply charm
Nope

**Comment by nobodyrandom** [comment]
OK i see the problem, but will need to board a train to get it fixed.

**Comment by nobodyrandom** [comment]
Check if the other two train area works, so I can get it all fixed in one go

**Comment by darkn123** [comment]
The other areas seem to work. Only having issues with supply schedule charms

**Comment by nobodyrandom** [comment]
OK
Pushed 2.1.18b to fix it

**Comment by nobodyrandom** [comment]
It is just due to firefox not supporting the function used to read the text on the site =,=

IE, Chrome and Opera supports them fine tho

**Comment by darkn123** [comment]
Function loadTrain isnt working due to innertext

**Comment by nobodyrandom** [comment]
I would suggesting using chrome for now to bypass innertext. I can not switch all innerTexts into textContent due to them being very different, I'll switch it slowly as I try all the B bots out.

**Comment by darkn123** [comment]
Trap Check Time Offset is in minutes and not seconds

I cannot seem to put a custom figure in Trap Check Time Offset. It keeps resetting to something else

**Comment by nobodyrandom** [comment]
Everything here should be fixed...
