### ISSUE TITLE
"Can not hunt without cheese" - Jan28 Patch

### ISSUE THREAD

**Issue by KaitoKid** [nobodyrandom/mhAutobot#39]
There's a whole mess of patch notes from today's update. https://www.mousehuntgame.com/newspost.php?news_post_id=429

Many community-written tools are broken until we get a chance to fix them

Could be this:
>Fixed Camp Page trap selector bait image not updating when disarmed.

**Comment by nobodyrandom** [comment]
Please drop me a PR, I do not have much time to fix sorry.

**Comment by hongshaoyang** [comment]
Looks like #40 helped.

**Comment by KaitoKid** [comment]
Confirmed that #40 fixes it
