### ISSUE TITLE
Firefox version not working

### ISSUE THREAD

**Issue by taratarat** [nobodyrandom/mhAutobot#5]
after installing both revamp and revamp enhanced version, i don't see the familiar preferences header at the top of the screen. There is no horn timer displayed on the tab as well. Not sure if your script is actually working.

**Comment by nobodyrandom** [comment]
Sorry didnt see your message here,
Can I double check that you are on version 1.4.417 using greasyMonkey on chrome or firefox?

**Comment by nobodyrandom** [comment]
One more thing I want to double check is that you are using the old UI right?

**Comment by autobotrevamp** [comment]
Old UI on greasemonkey on firefox/firefox forks like pale moon etc does not work with script. CNN script autohorns but extra features don't work, just for reference. Script works fine on chrome with tampermonkey.


Off the topic of this bug report, can you add support for sounding 2 accounts at once? when having 2 accounts logged in (1 fb and 1 on mousehuntgame) the bot runs into problems.

**Comment by autobotrevamp** [comment]
Old UI with script loaded in greasemonkey on firefox/firefox based browsers ie pale moon etc do not work with script. Old CNN script works for autohorn but not the specific area like LG.
Works find on chrome using tampermonkey extension.

Offtopic: Can support for 2 accounts on 1 browser be implemented? 1 on FB and one on the offsite. Script does not really work when using 2 accounts. Thanks!

**Comment by nobodyrandom** [comment]
2 Accounts is not supported just yet, cause preferences are saved on browser... I can give that a tweak to make it work

For firefox, I'll give it a thorough test this weekend, hold on tight :)

**Comment by autobotrevamp** [comment]
Thanks! 
Another bug: arming of the 3 charms doesn't seem to work properly, when in cursed city. Trap change was fine, but charm arming did not work.

**Comment by nobodyrandom** [comment]
okie will check that over

**Comment by nobodyrandom** [comment]
OK just ran through checks in firefox, seems like its a problem with greasemonkey/firefox build, my code might need a rebuild for it to work there. It'll be on my todo list but might take some time.

Ran a two account check, it seems to work. What problems are you encountering? Are the preferences diff on both accounts?

I've put more delays in trap arming, see if that helps

Pls update to ver 508

**Comment by autobotrevamp** [comment]
I'll give it a shot again. Last time I tried 2 accounts the HUD would say Horn synchronising after a few hunts and then stay there forever.

**Comment by nobodyrandom** [comment]
OK since MH has now released beta UI for all users, I'll need to focus my time on developing the bot for that.

For LG areas, a temporary fix is to reload the page, if the extra time still does not work

**Comment by nobodyrandom** [comment]
New UI version is more so finished, whats the status on this bug?

**Comment by autobotrevamp** [comment]
Still not working on firefox, I think double accounts work.

**Comment by nobodyrandom** [comment]
Progress on firefox bug: none (cant seem to find what is causing the error)
Double account will work if you enable the script in incognito+normal on chrome, as incog does not save user preferences, but you will have to change your settings every time you reopen the window

**Comment by nobodyrandom** [comment]
OK, I have been able to write a build of the bot that works with firefox.
The problem seems to be in the way greasemonkey links up @requred scripts
Will update all bots to work for firefox asap
(Pushing it out as version 2.0)

**Comment by nobodyrandom** [comment]
FIREFOX BUILD IS NOW DONE.
Ver 2.0.1a is available for download on openuserjs and greasyfork
