### ISSUE TITLE
can't get it work on google chrome

### ISSUE THREAD

**Issue by mousehunt** [nobodyrandom/mhAutobot#7]
Hi, my chrome is Version 40.0.2214.111 m, i can't seems to make it work, any advice?

**Comment by nobodyrandom** [comment]
Are you the same person who submitted this? http://prntscr.com/63ebni

**Comment by mousehunt** [comment]
yes, thats me :D

**Comment by nobodyrandom** [comment]
Give me a sec
Ill check the chrome extension version

**Comment by mousehunt** [comment]
thank you!

**Comment by nobodyrandom** [comment]
Try uninstalling the extension
And reinstalling this version: https://github.com/nobodyrandom/mhAutobot/raw/master/chromeExtension.crx

**Comment by nobodyrandom** [comment]
Alternatively try installing tampermonkey (https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo) and installing my script on there through this link (https://greasyfork.org/en/scripts/6092-mousehunt-autobot-revamp)

This method allows you to always get the newest version of the bot

**Comment by mousehunt** [comment]
ok, this thing shows up http://prntscr.com/63eju7
will see how it works for next hunt. and question, what will it do when kr? alert with sound or auto clear?  
thanks in advance. :D

**Comment by nobodyrandom** [comment]
Check the preferences, you can alert with popup and/or with sound

Auto clear is not supported due to new UI changes and danger of getting banned

**Comment by mousehunt** [comment]
yup, i just want to make sure, kr sound work perfectly for years, so will stick with that option, thank you so much!

**Comment by mousehunt** [comment]
and i was using ooi autobot ver 1.28 before until i can't get the kr sound to work, so for this version, what should i check to make sure the sound work? thanks again :)

**Comment by mousehunt** [comment]
http://prntscr.com/63eo8z not sounding....
