### ISSUE TITLE
is me again

### ISSUE THREAD

**Issue by mousehunt** [nobodyrandom/mhAutobot#8]
i see the thread is close, so i make a new one... sorry. http://prntscr.com/63eo8z
it is not sounding, the "next hunter horn time" just keep showing "loading..."

**Comment by nobodyrandom** [comment]
wait, are you on old UI?

**Comment by mousehunt** [comment]
yes, old ui.

**Comment by nobodyrandom** [comment]
Version 1.5 with a y suffix will only work on the new ui

**Comment by nobodyrandom** [comment]
use version 1.4 with a,b, or c suffix

**Comment by mousehunt** [comment]
ok, i'll install it, thanks for the quick reply. :D

**Comment by nobodyrandom** [comment]
you can always switch to the new UI as well

**Comment by nobodyrandom** [comment]
its just under support, user preferences

**Comment by mousehunt** [comment]
ok, will try it. thanks!

**Comment by nobodyrandom** [comment]
Got it done? If so, I'll close this thread

**Comment by mousehunt** [comment]
yes, it is done. :)
